export const INTERESTS = [
  "Street Food",
  "Fine Dining",
  "Coffee & Cafes",
  "Wine & Cocktails",
  "Cooking Classes",
  "Food Markets",
  "Hiking & Trails",
  "Beaches",
  "Water Sports",
  "Skiing & Snowboarding",
  "Cycling",
  "Rock Climbing",
  "Museums",
  "Art Galleries",
  "Live Music",
  "Theater & Performances",
  "Architecture",
  "Photography",
  "History & Ruins",
  "Religious Sites",
  "Local Festivals",
  "Language & Culture",
  "Shopping & Markets",
  "Nightlife",
  "Wellness & Spas",
  "Yoga & Meditation",
  "Wildlife & Nature",
  "National Parks",
  "Road Trips",
  "Train Journeys",
  "Volunteering",
  "Digital Nomad Life",
] as const;

export type Interest = (typeof INTERESTS)[number];
